### ISSUE TITLE
Waqf2 license ?

### ISSUE THREAD

**Issue by aelmahmoudy** [ojuba-org/hijra#1]
السلام عليكم،

  لا أجد نسخة من رخصة وقف2 على موقع أعجوبة. ممكن أن يدلني أحد على الرابط ؟

**Comment by aelmahmoudy** [comment]
وجدت الرخصة في 
http://ojuba.org/wiki/waqf-2.0/%D8%B1%D8%AE%D8%B5%D8%A9_%D9%88%D9%82%D9%81_%D8%A7%D9%84%D8%B9%D8%A7%D9%85%D8%A9

هل من الممكن ترجمة انجليزية لهذه الرخصة ؟

**Comment by muayyad-alsadi** [comment]
عذرا اخي الحبيب.  اخونا مصعب عمل الإصدار الثاني بحجة تيسير القبول لها بين
osi و gpl-compatible فجعلها غير ملزمة.  لكنه فتر عن قبولها وترجمتها

**Comment by aelmahmoudy** [comment]
@moceap أرجو أن تهم في مسألة الترجمة لأن عدم وجودها يمنع وضعها في اصدار Debian
